name: 'Workflow CI Analytics'
description: 'Send Github Data Analytics to the Data Warehouse'
inputs:
  created_at:
    description: 'Timestamp when the job was created'
    required: true
  started_at:
    description: 'Timestamp when the job was started'
    required: true
  completed_at:
    description: 'Timestamp when the job was completed'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
  post-if: 'success()'
