name: 'Workflow CI Analytics'
description: 'Notify upon workflow failure/success'
inputs:
  created_at:
    description: 'Timestamp when the job was created'
    required: true
    default: ''
  started_at:
    description: 'Timestamp when the job was started'
    required: true
    default: ''
  completed_at:
    description: 'Timestamp when the job was completed'
    required: true
    default: ''
  github-token:
    description: 'Status of the current run'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
  post-if: 'success()'
