export enum Inputs {
  ProjectId = 'project_id',
  Dataset = 'dataset',
  Table = 'table',
  CreatedAt = 'created_at',
  StartedAt = 'started_at',
  CompletedAt = 'completed_at',
  MatrixName = 'matrix_name',
  MatrixValue = 'matrix_value',
  Result = 'result',
  Draft = 'draft',
  JobLink = 'job_link',
  TriggeringActor = 'triggering_actor',
  RunAttempt = 'run_attempt',
  HeadRef = 'head_ref',
  BaseRef = 'base_ref',
  RunnerType = 'runner_type',
  RunnerName = 'runner_name',
}
